/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billzz;

import billzz.Database.SqlConnection;
import java.awt.Color;
import java.util.Date;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Anuj
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 181, 246));
        BillAddLabel.setForeground(Color.WHITE);
        CustomerInfoLabel.setForeground(Color.WHITE);
        EmailLabel.setForeground(Color.WHITE);
        LocalityLabel.setForeground(Color.WHITE);
        MobileNoLabel.setForeground(Color.WHITE);
        NameLabel.setForeground(Color.WHITE);
        submit.setBackground(Color.decode("#50AF00"));
        submit.setForeground(Color.WHITE);
         pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerInfoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        LocalityLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MobileNoLabel = new javax.swing.JLabel();
        BillAddLabel = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobileNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        billAddress = new javax.swing.JTextArea();
        locality = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        CustomerInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerInfoLabel.setText("CUSTOMER INFORMATION");

        NameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        NameLabel.setText("Full Name");

        LocalityLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LocalityLabel.setText("Locality");

        EmailLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        EmailLabel.setText("E-mail");

        MobileNoLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        MobileNoLabel.setText("Mobile No.");

        BillAddLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BillAddLabel.setText("Billing Address");

        customerName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        email.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        mobileNumber.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        mobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumberActionPerformed(evt);
            }
        });

        billAddress.setColumns(20);
        billAddress.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        billAddress.setRows(5);
        jScrollPane2.setViewportView(billAddress);

        locality.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        locality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localityActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        submit.setText("Add");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocalityLabel)
                            .addComponent(EmailLabel)
                            .addComponent(MobileNoLabel)
                            .addComponent(BillAddLabel)
                            .addComponent(NameLabel))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email)
                            .addComponent(locality)
                            .addComponent(customerName)
                            .addComponent(mobileNumber)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(CustomerInfoLabel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(customerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalityLabel)
                    .addComponent(locality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileNoLabel)
                    .addComponent(mobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(BillAddLabel)))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
      
        String customer_name = customerName.getText();
        String locality_txt  = locality.getText();
        String bill_address = billAddress.getText();
        String e_mail = email.getText();
        String mobile_no = mobileNumber.getText();
        String last_bill_date = dateFormat.format(date); // todays date
        String last_bill_amt = 0 +"";
        String last_pay_time = dateFormat.format(date);
        String unbilled_amt = 0+"";
        
        if(customer_name.equals("") || locality_txt.equals("") || bill_address.equals("")|| 
                e_mail.equals("") ||mobile_no.equals("") || last_bill_date.equals("") || last_bill_amt.equals("")|| last_pay_time.equals("")
                || unbilled_amt.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Fill All Feilds", "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                Statement stmt = SqlConnection.getStat();
                String insertCustomer = "insert into customer(full_name, locality, email, mobile , billing_address, last_bill_date, last_bill_amount, last_pay_time, unbilled_amount)\n"
                +"values('"+customer_name+"' , '"+locality_txt+"' , '"+e_mail+"' , '"+mobile_no+"' , '"+bill_address+"' , '"+last_bill_date+"\n"
                        + "' , '"+last_bill_amt+"' , '"+last_pay_time+"' , '"+unbilled_amt+"')";
                stmt.execute(insertCustomer);
                this.setVisible(false);
//                javax.swing.JOptionPane.showMessageDialog(null, "Customer Added Successfully", "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, e.toString(), "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_submitActionPerformed

    private void localityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localityActionPerformed

    private void mobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BillAddLabel;
    private javax.swing.JLabel CustomerInfoLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel LocalityLabel;
    private javax.swing.JLabel MobileNoLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextArea billAddress;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField email;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locality;
    private javax.swing.JTextField mobileNumber;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
