/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billzz;

import Avator.CreateAvator;
import billzz.Database.SqlConnection;
import billzz.Model.Customer;
import billzz.Model.Product;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author virk computerZ
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(100, 181, 246));
        BillAddLabel.setForeground(Color.WHITE);
        CustomerInfoLabel.setForeground(Color.WHITE);
        EmailLabel.setForeground(Color.WHITE);
        LocalityLabel.setForeground(Color.WHITE);
        MobileNoLabel.setForeground(Color.WHITE);
        NameLabel.setForeground(Color.WHITE);
        jButton1.setBackground(Color.decode("#50AF00"));
        jButton1.setForeground(Color.WHITE);
         pack();
        setLocationRelativeTo(null);
        try{
             Statement stmt = SqlConnection.getStat();
            String sql = "select * from customer where id = '"+Customer.id+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                editName.setText(rs.getString("full_name"));
                editAddress.setText(rs.getString("billing_address"));
                editEmail.setText(rs.getString("email"));
                editMobile.setText(rs.getString("mobile"));
                editLocality.setText(rs.getString("locality"));
            }
        }catch(Exception e){
             javax.swing.JOptionPane.showMessageDialog(null, e.toString(), "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        editName.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerInfoLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        LocalityLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        MobileNoLabel = new javax.swing.JLabel();
        BillAddLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        editName = new javax.swing.JTextField();
        editLocality = new javax.swing.JTextField();
        editEmail = new javax.swing.JTextField();
        editMobile = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        editAddress = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerInfoLabel.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        CustomerInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerInfoLabel.setText("CUSTOMER INFORMATION");

        NameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        NameLabel.setText("Full Name");

        LocalityLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        LocalityLabel.setText("Locality");

        EmailLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        EmailLabel.setText("E-mail");

        MobileNoLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        MobileNoLabel.setText("Mobile No.");

        BillAddLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BillAddLabel.setText("Billing Address");

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        editName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editLocality.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editEmail.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editMobile.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editAddress.setColumns(20);
        editAddress.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editAddress.setRows(5);
        jScrollPane1.setViewportView(editAddress);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(LocalityLabel)
                            .addComponent(EmailLabel)
                            .addComponent(MobileNoLabel)
                            .addComponent(BillAddLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editMobile, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editLocality, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(CustomerInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalityLabel)
                    .addComponent(editLocality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MobileNoLabel)
                    .addComponent(editMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BillAddLabel)))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String flocality = editLocality.getText();
        String fmobile = editMobile.getText();
        String femail = editEmail.getText();
        String faddress = editAddress.getText();
        int id = Integer.parseInt(Customer.id);
         if(flocality.equals("") || faddress.equals("")|| 
                femail.equals("") ||fmobile.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Fill All Feilds", "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                Statement stmt = SqlConnection.getStat();
                String updateCustomer = "update customer set locality='"+flocality+"',email='"+femail+"',mobile='"+fmobile+"', billing_address='"+faddress+"' where id = "+id;
                stmt.execute(updateCustomer);
                this.setVisible(false);
//                javax.swing.JOptionPane.showMessageDialog(null, "Customer Information Updated Successfully", "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, e.toString(), "InfoBox:",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BillAddLabel;
    private javax.swing.JLabel CustomerInfoLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel LocalityLabel;
    private javax.swing.JLabel MobileNoLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextArea editAddress;
    private javax.swing.JTextField editEmail;
    private javax.swing.JTextField editLocality;
    private javax.swing.JTextField editMobile;
    private javax.swing.JTextField editName;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
